micronaut:
  application:
    name: people
  server:
    port: -1
#  router:
#    static-resources:
#      swagger:
#        paths: classpath:META-INF/swagger
#        mapping: /swagger/**
#  config-client:
#    enabled: true
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            validation:
              secret: pleaseChangeThisSecretForANewOne
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:172.20.238.5}:${CONSUL_PORT:8500}"
endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

